### ISSUE TITLE
Finding a pathway for a given gene

### ISSUE THREAD

**Issue by premadh** [BioPAX/paxtoolsr#2]
As discussed here: https://www.biostars.org/p/188779/#191357
I was trying get the pathways to which a gene is involved. But when I execute 

`geneSets <- downloadPc2("Pathway Commons.7.All.GSEA.hgnc.gmt.gz")`

I get the error 
`Error in strsplit(tmp3, ";") : non-character argument`

I looked into the function itself: Line 29

`idx <- grepl(".gz", links)`

Here `idx` becomes FALSE for all cases

`print(links)` gives :

 `href 
                                            "http://www.pathwaycommons.org" 
                                                                       href 
                                                                        "#" 
                                                                       href 
                    "/pc2/home;jsessionid=408C224190DDD16A0058C5FB82E780FE" 
                                                                       href 
             "/pc2/home;jsessionid=408C224190DDD16A0058C5FB82E780FE#search" 
                                                                       href 
                "/pc2/home;jsessionid=408C224190DDD16A0058C5FB82E780FE#get" 
                                                                       href 
           "/pc2/home;jsessionid=408C224190DDD16A0058C5FB82E780FE#traverse" 
                                                                       href 
              "/pc2/home;jsessionid=408C224190DDD16A0058C5FB82E780FE#graph" 
                                                                       href 
       "/pc2/home;jsessionid=408C224190DDD16A0058C5FB82E780FE#top_pathways" 
                                                                     href    "/pc2/home;jsessionid=408C224190DDD16A0058C5FB82E780FE#parameter_values"                                                                        href              "/pc2/datasources;jsessionid=408C224190DDD16A0058C5FB82E780FE"                                                                        href                "/pc2/downloads;jsessionid=408C224190DDD16A0058C5FB82E780FE"                                                                        href   
                                                                "formats"                                                                        href                                  
 "http://www.pathwaycommons.org/archives/"                                                                      
  href 
                                       "http://www.biopax.org/paxtools"   
                                                                     href 
"https://github.com/BioPAX/Paxtools/wiki/PatternBinaryInteractionFramework" 
                                                                       href 
                                 "https://pathwaycommons.github.io/cpath2/"  
                                                                      href 
                                                     "http://baderlab.org/"  
                                                                      href     
                                "http://www.sanderlab.org"`

Consequently, `tmp` and `tmp2` are both empty. Can this be fixed?

**Comment by cannin** [comment]
There are two issues here: 

1: I fixed the strsplit() issue recently. Pathway Commons moved where files are hosted causing this issue. You need the latest development version from GitHub using devtools (check the [README](https://github.com/BioPAX/paxtoolsr) for instructions). The fixed will be on Bioconductor 3.3 soon. 

2: Pathway Commons recently released a new version. If you run: 

downloadPc2() You'll see the updated file names, making the command now: 

```
downloadPc2("PathwayCommons.8.All.GSEA.hgnc.gmt.gz")
```

Check the documentation if you want the older version.
