### ISSUE TITLE
Find all the genes involved in a pathway

### ISSUE THREAD

**Issue by Kamalika17** [BioPAX/paxtoolsr#7]
Hi,

I have an input gene. I want to get all the pathways that the gene is participating in and the other genes in the respective pathways. How can I get this information?

gene -> get all pathways (pathway1, pathway2 etc) -> get all other genes involved in these pathways (pathway1, pathway2)

Thanks

**Comment by cannin** [comment]
@Kamalika17 My suggestion download: 

https://www.pathwaycommons.org/archives/PC2/v12/PathwayCommons12.All.hgnc.gmt.gz

then using this function: https://github.com/cannin/listutils/blob/master/R/searchListOfVectors.R

Run something like this: 

```
library(paxtoolsr)
library(listutils)

input_gene <- "NOS3"
gmt <- readGmt("~/Downloads/PathwayCommons12.All.hgnc.gmt")

tmp <- searchListOfVectors(input_gene, gmt, useNames=FALSE)
pathway_ids <- tmp[[input_gene]]

gmt[pathway_ids]
```

**Comment by Kamalika17** [comment]
Thank you for your response. How can I get the interactions as well between the genes?

**Comment by cannin** [comment]
Expanded answer: 

NOTE: The URI should look like a URL web link. 

```
library(paxtoolsr)
library(listutils)

input_gene <- "NOS3"
gmt <- readGmt("~/Downloads/PathwayCommons12.All.hgnc.gmt")
tmp <- searchListOfVectors(input_gene, gmt, useNames=TRUE)
pathway_ids <- tmp[input_gene]

gmt[pathway_ids]

cur_pathway_id <- 8
uri <- pathway_ids[cur_pathway_id]
sif <- getPc(uri, format = "SIF")

interactions <- filterSif(sif, ids = input_gene)
```

**Comment by Kamalika17** [comment]
Thanks a lot! This is very helpful.

**Comment by cannin** [comment]
Closing the issue for now. Remember to cite paxtoolsr: https://pubmed.ncbi.nlm.nih.gov/26685306/
