### ISSUE TITLE
Error while parsing "PathwayCommons12.All.hgnc.txt" file using readSifnx

### ISSUE THREAD

**Issue by Kamalika17** [BioPAX/paxtoolsr#9]
Hi,

I am trying to get all the pathway information from the PathwayCommons12.All.hgnc.txt file. I am using the paxtoolsr function readSifnx for the same. However, it is throwing the following error:

  `Error in checkInputFilePc(inputFile) : 
  ERROR: A maximum file size limit of 1GB has been placed on files being read. Reading larger files with this function may be very slow. Please contact package author for workarounds.`
  
  Please help me resolve this. 
  
  Thanks a lot!

**Comment by cannin** [comment]
@Kamalika17 please update to the latest version and it should work

```
setRepositories(ind=1:6)
options(repos="http://cran.rstudio.com/")
if(!require(remotes)) { install.packages("remotes") }
library(remotes) 

remotes::install_github("BioPAX/paxtoolsr")
remotes::install_github("BioPAX/paxtoolsr", args="--no-multiarch") # On Windows, 64-bit
```

**Comment by Kamalika17** [comment]
Thank you very much. That solved the issue.
